### PR TITLE
Checkbox validation for question2

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #9

### CODE REVIEW

**Comment by dmotts** [comment]
@Brijeshthummar02 Your pull request is under review.

**Comment by Brijeshthummar02** [comment]
@dmotts any update?

**Comment by dmotts** [comment]
Hey @Brijeshthummar02, I'm still reviewing. It's freeze on the first slide. I don't know why so I'm looking into it. Thank you for your patience.

**Comment by dmotts** [comment]
Hey @Brijeshthummar02, it may take me a while to debug, as it is the weekend. I need to setup the structure of the repo so developers can properly test the app without hassle, so I may focus on that aspect for future updates/contributions.

Good to have you on the team btw! 🤝

**Comment by Brijeshthummar02** [comment]
@dmotts no worries, take your time, i would love to contribute to such repos.

**Comment by dmotts** [comment]
😆🤣 That's awesome, @Brijeshthummar02! As you are so eager, and because of your enthusiasm. You have inspired a future project that would be centred around the developers but I'll push this project in stages. If you want to get involved I'll start an official team for this specific project. Keep up the good work!

**Comment by Brijeshthummar02** [comment]
yeah you can add me to the team.

**Comment by dmotts** [comment]
Great! I'll keep you posted and thank you for joining @Brijeshthummar02. I really appreciate it. 🌟🌟🌟

**Comment by dmotts** [comment]
Hey @Brijeshthummar02, sorry about the late response however, I will be going through your PR today.

**Comment by dmotts** [comment]
Okay @Brijeshthummar02, I'm going to merge this PR to the staging branch so it could be deployed to the staging deployment. This should allow you to preview the app, and see what's happening with the app. Now, I'm a little rusty with these GitHub workflows so please bare with me.

Afterwards, I'll set it up so you can push to that specific branch to debug the code through that deployment. I'll keep you posted.

**Comment by dmotts** [comment]
Here's a screenshot of Step 1, from there the 'Next' button no longer works.

IMG_20241014_205906

Here's the deployment link to see for yourself: 
https://ai-insights-preview.up.railway.app/

Unfortunately, only 'Step 2' is supposed to be a multiple select option. However, in this case it seems like it has also affected 'Step 1'.

You may let me know if you're still interested in accomplishing this task 

Remember, we are all here to help each other grow as developers. Have fun with it @Brijeshthummar02  and thanks again for your contributions!

**Comment by Brijeshthummar02** [comment]
@dmotts can we create new issue regarding this??

**Comment by dmotts** [comment]
Of course we can @Brijeshthummar02!

This is all part of the journey. 😃

The next phase would be to attract more developers to join in for support.

Please share your thoughts, do not hold back and always be yourself. 

I love coding and I wish I had as much enthusiasm as you years ago but everything happens for a reason is what I believe. So keep aiming for the moon, cause if you miss. You still be among the stars.

So, don't stop trying. DO make mistakes and fail over and over and over again!

That's the secret to success.  😎

Teamwork makes the dream work! 

Let's go! 💪

**Pull request merged**
